POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "John Doe with billing account ", 
    "email": "john.the.doe@example.com",
    "address": "123 Main St, Anytown, Dunzledorf",
    "dateOfBirth": "1990-01-01",
    "registeredDate": "2024-06-15"
}


